tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/test/esf_test_0001.tcl
tclapp/xilinx/projutils/test/esf_test_0002.tcl
tclapp/xilinx/projutils/test/wpt_test_0001.tcl
tclapp/xilinx/projutils/test/wpt_test_0002.tcl

Please merge to 2015.1 (App:projutils)
Thanks

Support for exporting simulation sources for export_simulation

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge to 2015.1 (app:projutils)
Thanks

Fix for the file formats

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge to 2015.1 (app:projutils)
Thanks

- support for the windows platform

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge to 2015.1 (app:projutils)
Thanks

- generate README.txt file

---

catalog/2015.1/xilinx/ultrafast/app.xml
catalog/catalog_2015.1.xml
tclapp/xilinx/ultrafast/app.xml
tclapp/xilinx/ultrafast/checklist.tcl
tclapp/xilinx/ultrafast/checklist_pkg.tcl
tclapp/xilinx/ultrafast/create_cdc_reports.tcl
tclapp/xilinx/ultrafast/pkgIndex.tcl
tclapp/xilinx/ultrafast/report_io_reg.tcl
tclapp/xilinx/ultrafast/report_reset_signals.tcl
tclapp/xilinx/ultrafast/test/check_pll_connectivity_0001.test
tclapp/xilinx/ultrafast/test/create_cdc_reports_0001.test
tclapp/xilinx/ultrafast/test/report_clock_topology_0001.test
tclapp/xilinx/ultrafast/test/report_io_reg_0001.test
tclapp/xilinx/ultrafast/test/report_reset_signals_0001.test
tclapp/xilinx/ultrafast/test/test.tcl

Misc updates for UltraScale. Added unit tests. (ultrafast)

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge to 2015.1 (Apps: simulation and projutils)
Thanks

- support for the xpm library

---

tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

please merge to 2015.1 (app:xsim)

- generate IP C-models library

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/register_options.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

- Support for the --relax switch for xvlog and xvhdl
Please merge to 2015.1 (projutils and xsim sim app). Thanks.

- Support for the secureip library compilation for single-step flow

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/register_options.tcl
tclapp/xilinx/xsim/xsim.tcl

- fixed few issues with the single step flow
Please merge to 2015.1 (projutils and xsim app)  - priority medium
Thanks

- fixed the IP verification check to look for is_ip_generated_sim

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/ies/sim.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/sim.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge to 2015.1 (sim and projutils apps) - Priority:high
Thanks

- support for core-container files export

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/ies/sim.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/write_project_tcl.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/sim.tcl
tclapp/xilinx/vcs/vcs.tcl

please merge to 2015.1 (sim and projutils app), thanks

2015.1 CR fixes

---

tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl

please merge 'modelsim' and 'questa' app version updates to 2015.1 - thanks

- updated app version

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/ies/sim.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/sim.tcl
tclapp/xilinx/vcs/vcs.tcl

please merge "ies" "modelsim" "questa" "vcs" sim apps to master (HEAD), thanks

- fixed lib map path to absolute for -absolute_path

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

- fixed issue with the top library calculation by refactoring the code
2015.1 CR fixes: Please merge all sim apps for 2015.1 - priority high
Thanks

- fetch unique wcfg files from xsim.view property

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/get_clock_interaction.tcl
tclapp/xilinx/designutils/insert_buffer.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/utils.tcl
tclapp/xilinx/designutils/write_template.tcl

This pull request is for 2015.1.
Thank you for merging.

Fixed some improper command line arguments (xilinx::designutils)

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/doc/export_bd_synth
tclapp/xilinx/projutils/export_bd_synth.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

2015.1 cr (850265) : please merge projutils to 2015.1 - priority medium

- support for the -force switch on export_bd_synth

---

tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/register_options.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

- support for quit on error for GUI mode
2015.1 CR fixes (820503, 844176) - Please merge sim apps for 2015.1, priority high
thanks

- support for fetching all signals for saif

---

tclapp/xilinx/designutils/convert_muxfx_to_luts.tcl

Updated convert_muxfx_to_luts to add better messaging and lower some CWs to warnings

Updated convert_muxfx_to_luts

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/convert_muxfx_to_luts.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/utils.tcl

To be merged to 2015.1 and 2015.3

Merged pull request 425 and updated designutil version to 1.13 (xilinx::designutils)

---

tclapp/xilinx/designutils/create_combined_mig_io_design.tcl

Fixed issue in which files were added remotely rather than being imported into the new project.  Added error checking for creation of new project for better messaging to user

Updated create_combined_mig_io_design tcl script

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/create_combined_mig_io_design.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/utils.tcl

updated designutil version to 1.14 to include changes to create_combined_mig_io_design (designutils)

---

tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

cr:852869 (srcb approved) - please merge to master for 2015.1 and 2015.3 - priority high
thanks

852869-fixed XSim error detection proc to look for elaborate.log

---

tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl

cr:849403 (srcb approved) - please merge to master for 2015.1 and 2015.3 - priority high
thanks

Set PATH to point to 32-bit libraries

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

please merge (xsim::projutils) into master for 2015.2, thanks

852222 - fixed script file name processing code for multiple IP's

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/write_project_tcl.tcl

cr:815260 (approved for .2) - please merge xilinx::projutils app for 2015.2 (master), thanks

815260 - add constrs from local if -no_copy_sources is set

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/populate_sim_repo.tcl
tclapp/xilinx/projutils/projutils.tcl

please merge xilinx::projutils app for 2015.3 (2015.3-dev)

populate_sim_repo now exports stub files

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

cleaned up central repo references and fixed xsim includes

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/populate_sim_repo.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

fix all simulators system IP resolution for IPI designs

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/ies/sim.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

fixed VCS simulator so that it correctly generates scripts

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/ies/sim.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/sim.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P1), thanks

- fix for 2015.3 CRs 885698,878323

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P1), thanks

- fix for 2015.3 CR 878593

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_ip_user_files.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P1), thanks

- fix for 888062

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P1), thanks

- fix for 894208

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/ies/sim.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_ip_user_files.tcl
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/sim.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P2), thanks

- fix for 885729,877579,871301,874331,873526

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_bd_synth.tcl
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/write_project_tcl.tcl

Please merge this with 2016.1.

fixed a spelling error in export_bd_synth description

---

tclapp/mycompany/myapp6/a_test_file
tclapp/mycompany/myapp6/pkgIndex.tcl

I will merge this myself. Thanks!

Test commit ids from fork

---

tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge following apps into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P2):-
xsim
thanks

- fix for 864078

---

tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/sim.tcl
tclapp/xilinx/vcs/vcs.tcl

Please merge following sim apps into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P2):-
modelsim
questa
vcs
thanks

- fix for 909998, 910309

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge following apps into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P2):-
xsim
modelsim
questa
ies
vcs
projutils
thanks

- fix for 866839 (merged Nik's fix)

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_ip_user_files.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge following app into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P2), thanks
projutils

- fix for 878209

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/ies/sim.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/sim.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/sim.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/sim.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/sim.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge following sim apps into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P2)
xsim
modelsim
questa
ies
vcs
thanks

- fix for 869334

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge following app into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority-P2)
projutils
thanks

- fix for 911413

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge following app into XilinxTclStore master and update 2015.3, 2015.4 and 2016.1 catalogs (priority:p1)
projutils
thanks

- fix for 911761 (merged Nik's pull 491)

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_ip_user_files.tcl
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/setup_ip_static_library.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

Please merge following apps into XilinxTclStore master and update 2016.1 catalog (priority-P2)
projutils, xsim, modelsim, questa, ies, vcs
thanks

- support for pre-compiled ipstatic files from catalog

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/doc/export_simulation
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

Please merge following app into XilinxTclStore master and update 2016.1 catalog (priority-P2)
projutils
thanks

- fix for 912716

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/bisect_pblock.tcl
tclapp/xilinx/designutils/check_cdc_paths.tcl
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/get_host_platform.tcl
tclapp/xilinx/designutils/get_inter_slr_nets.tcl
tclapp/xilinx/designutils/get_leaf_cells.tcl
tclapp/xilinx/designutils/get_pid_mem.tcl
tclapp/xilinx/designutils/get_sll_nets.tcl
tclapp/xilinx/designutils/highlight_enable_signal_sites.tcl
tclapp/xilinx/designutils/insert_buffer.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl
tclapp/xilinx/designutils/read_file_regexp.tcl
tclapp/xilinx/designutils/reapply_iostandard.tcl
tclapp/xilinx/designutils/report_all_primitives.tcl
tclapp/xilinx/designutils/report_cells_fanout.tcl
tclapp/xilinx/designutils/report_cells_loc.tcl
tclapp/xilinx/designutils/report_critical_hfn.tcl
tclapp/xilinx/designutils/report_hier_util.tcl
tclapp/xilinx/designutils/report_parts.tcl
tclapp/xilinx/designutils/source_path.tcl
tclapp/xilinx/designutils/write_template.tcl

Minor documentation update (xilinx::designutils)

---

tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/questa/register_options.tcl
tclapp/xilinx/questa/sim.tcl

Please merge following app into XilinxTclStore master and update 2016.1 catalog (priority-P1)
questa
thanks

- fix for 913003

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/setup_ip_static_library.tcl

Please merge following apps into XilinxTclStore master and update 2016.1 catalog (priority-P2)
projutils
thanks

- print progress messages

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/get_inter_slr_nets
tclapp/xilinx/designutils/get_inter_slr_nets.tcl
tclapp/xilinx/designutils/pkgIndex.tcl

For 2015.3 only. Will do the merge.

Runtime improvement for get_inter_slr_nets (xilinx::designutils)

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_ip_user_files.tcl
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl

projutils - commented several unused procs

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/insert_buffer
tclapp/xilinx/designutils/doc/insert_buffer_chain
tclapp/xilinx/designutils/doc/insert_clock_probe
tclapp/xilinx/designutils/doc/remove_buffer
tclapp/xilinx/designutils/doc/rename_net
tclapp/xilinx/designutils/insert_buffer.tcl
tclapp/xilinx/designutils/pkgIndex.tcl

For master branch. Will do the merge myself.

Robustness and runtime improvement for insert_buffer.tcl (xilinx::designutils)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl

This is to merge with master branch for 2015.4. Will do the merge.

Enhancements to prettyTable (xilinx::designutils)

---

tclapp/xilinx/pcbutils/app.xml
tclapp/xilinx/pcbutils/doc/export_symbol
tclapp/xilinx/pcbutils/doc/legal.txt
tclapp/xilinx/pcbutils/export_symbol.tcl
tclapp/xilinx/pcbutils/revision_history.txt
tclapp/xilinx/pcbutils/tclIndex
tclapp/xilinx/pcbutils/test/export_symbol_0001.tcl

xilinx:pcbutils (2016.1-dev) export_symbol - Initial Release

Created export_symbol app

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl

I will merge this pull request for 2015.4

Fixed missing header inside CSV file (xilinx::designutils)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl
tclapp/xilinx/designutils/revision_history.txt

I will merge this pull request for 2016.1-dev

Fixed missing header inside CSV file + minor enhancements (xilinx::designutils)

---

tclapp/xilinx/pcbutils/app.xml
tclapp/xilinx/pcbutils/pcbutils.tcl
tclapp/xilinx/pcbutils/pkgIndex.tcl
tclapp/xilinx/pcbutils/revision_history.txt
tclapp/xilinx/pcbutils/test/export_symbol_0001.tcl

Remove temporary build directory after running test script

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_ip_user_files.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/revision_history.txt

please merge and update 2016.1 and 2016.3 catalogs (projutils app), p1 
thanks

947440 - support for the -reset switch for deleting ip instance files

---

tclapp/atrenta/spyglass/app.xml
tclapp/atrenta/spyglass/pkgIndex.tcl
tclapp/atrenta/spyglass/spyglass.tcl
tclapp/atrenta/spyglass/test/spy_run.prj
tclapp/atrenta/spyglass/write_spyglass_script.tcl

Request to merge the v1.5 of atrenta Tcl app. This includes only one modified file (write_spyglass_script.tcl)

Modified write_spyglass_script.tcl for atrenta tcl app 1.5

---

tclapp/atrenta/spyglass/app.xml
tclapp/atrenta/spyglass/pkgIndex.tcl
tclapp/atrenta/spyglass/spyglass.tcl
tclapp/atrenta/spyglass/write_spyglass_script.tcl
tt

This is my second pull request in the branch 2015.4

Modified write_spyglass_script.tcl for app version 1.5

---

tclapp/xilinx/ies/app.xml
tclapp/xilinx/ies/common/utils.tcl
tclapp/xilinx/ies/helpers.tcl
tclapp/xilinx/ies/ies.tcl
tclapp/xilinx/ies/pkgIndex.tcl
tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/common/utils.tcl
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/common/utils.tcl
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/questa/app.xml
tclapp/xilinx/questa/common/utils.tcl
tclapp/xilinx/questa/helpers.tcl
tclapp/xilinx/questa/pkgIndex.tcl
tclapp/xilinx/questa/questa.tcl
tclapp/xilinx/vcs/app.xml
tclapp/xilinx/vcs/common/utils.tcl
tclapp/xilinx/vcs/helpers.tcl
tclapp/xilinx/vcs/pkgIndex.tcl
tclapp/xilinx/vcs/vcs.tcl
tclapp/xilinx/xsim/app.xml
tclapp/xilinx/xsim/common/utils.tcl
tclapp/xilinx/xsim/helpers.tcl
tclapp/xilinx/xsim/pkgIndex.tcl
tclapp/xilinx/xsim/xsim.tcl

SRCB 2016.1, approval requested, but pending.

add VCOM VHDL file for XPM simulation, CR:947555

---

tclapp/xilinx/modelsim/app.xml
tclapp/xilinx/modelsim/helpers.tcl
tclapp/xilinx/modelsim/modelsim.tcl
tclapp/xilinx/modelsim/pkgIndex.tcl
tclapp/xilinx/modelsim/revision_history.txt

SRCB approved 2016.1 cr (modelsim app only). Please update all 2016.x catalogs (priority - p1), thanks

948081 - additional fix for xpm file processing for -of_objects

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/revision_history.txt

…unnecessary call)
Please merge to 2016.1 and update 2016.1 catalog (projutils app) - priority 1, thanks

948099 - do not re-generate mem files if generated earlier (removed 

---

tclapp/xilinx/designutils/create_combined_mig_io_design.tcl
tclapp/xilinx/designutils/timing_report_to_verilog.tcl

Updated to remove debug ports based on request

Update the create_combined_mig_io_design to ignore debug ports

---

catalog/2016.3/xilinx/designutils/app.xml
catalog/2016.3/xilinx/designutils/revision_history.txt
catalog/catalog_2016.3.xml
tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/convert_muxfx_to_luts.tcl
tclapp/xilinx/designutils/create_combined_mig_io_design.tcl
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/revision_history.txt
tclapp/xilinx/designutils/timing_report_to_verilog.tcl

List of changes:
timing_report_to_verilog.tcl
convert_muxfx_to_luts.tcl
create_combined_mig_io_design.tcl

Misc enhancements for designutils (2016.3-dev)

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/export_simulation.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/revision_history.txt

Please merge & update 2016.3 and 2016.4 catalog for projutils app (cr:960115 - SRCB approved, priority - 1), Thanks

- do not execute view signals command in simulate.do file

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/get_sll_nets.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/revision_history.txt

To be merged for Git master (Vivado 2016.3)

Improved support for UltraScale Plus (xilinx::designutils)

---

tclapp/aldec/activehdl/activehdl.tcl
tclapp/aldec/activehdl/app.xml
tclapp/aldec/activehdl/common/helpers.tcl
tclapp/aldec/activehdl/common/pkgIndex.tcl
tclapp/aldec/activehdl/common/sim.tcl
tclapp/aldec/activehdl/common/tclIndex
tclapp/aldec/activehdl/pkgIndex.tcl
tclapp/aldec/activehdl/register_options.tcl
tclapp/aldec/activehdl/revision_history.txt
tclapp/aldec/activehdl/sim.tcl
tclapp/aldec/riviera/app.xml
tclapp/aldec/riviera/common/helpers.tcl
tclapp/aldec/riviera/common/pkgIndex.tcl
tclapp/aldec/riviera/common/sim.tcl
tclapp/aldec/riviera/common/tclIndex
tclapp/aldec/riviera/pkgIndex.tcl
tclapp/aldec/riviera/register_options.tcl
tclapp/aldec/riviera/revision_history.txt
tclapp/aldec/riviera/riviera.tcl
tclapp/aldec/riviera/sim.tcl

Files grouped to speed up compilation. AXI-BFM settings updated. Pre/post tcl hooks added.

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/revision_history.txt
tclapp/xilinx/projutils/write_project_tcl.tcl

cr:971539 - return reconfig module sub-design files
Please merge to master and update 2017.2 catalogs (priority-p2), thanks

cr:974058 - return reconfig module sub-design files

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/insert_buffer.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl
tclapp/xilinx/designutils/revision_history.txt

To be merged to 2017.3-dev. I will do the merging.

Updated insert_buffer.tcl to better support UltraScale/UltraScale Plus. Minor update to prettyTable.

---

tclapp/aldec/activehdl/activehdl.tcl
tclapp/aldec/activehdl/app.xml
tclapp/aldec/activehdl/common/helpers.tcl
tclapp/aldec/activehdl/common/pkgIndex.tcl
tclapp/aldec/activehdl/common/sim.tcl
tclapp/aldec/activehdl/doc/legal.txt
tclapp/aldec/activehdl/pkgIndex.tcl
tclapp/aldec/activehdl/register_options.tcl
tclapp/aldec/activehdl/revision_history.txt
tclapp/aldec/activehdl/sim.tcl
tclapp/aldec/riviera/app.xml
tclapp/aldec/riviera/common/helpers.tcl
tclapp/aldec/riviera/common/pkgIndex.tcl
tclapp/aldec/riviera/common/sim.tcl
tclapp/aldec/riviera/doc/legal.txt
tclapp/aldec/riviera/pkgIndex.tcl
tclapp/aldec/riviera/register_options.tcl
tclapp/aldec/riviera/revision_history.txt
tclapp/aldec/riviera/riviera.tcl
tclapp/aldec/riviera/sim.tcl

Fixed bug with -scripts_only switch. Changed generated simulation scipt - now simulation works differently in batch mode. Removed fixed simulation resolution.
The changes were tested and approved by our SQA team.

Fixed bug with -scripts_only switch. Changed generated simulation scipt. Removed fixed simulation resolution.

---

tclapp/xilinx/projutils/create_bd_partition_def.tcl

remove exported proc

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/revision_history.txt
tclapp/xilinx/projutils/test/cpr_test_0001.tcl
tclapp/xilinx/projutils/test/test.tcl
tclapp/xilinx/projutils/write_project_tcl.tcl

GK: please merge to XilinxTclStore master and update 2017.3 catalog (priority-p2). Thanks.

983315, 984059- updated and enabled cpr_test_0001.tcl test

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/report_failfast
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt
tclapp/xilinx/designutils/tclIndex

Added report_failfast. Updated prettyTable (xilinx::designutils)

---

tclapp/xilinx/projutils/app.xml
tclapp/xilinx/projutils/copy_run.tcl
tclapp/xilinx/projutils/pkgIndex.tcl
tclapp/xilinx/projutils/projutils.tcl
tclapp/xilinx/projutils/revision_history.txt
tclapp/xilinx/projutils/write_project_tcl.tcl

985747: delete run if report strategy recreation fails
GK: please merge projutils app into master and update **2017.4 catalog ONLY** (priority-2), thanks

986161: update write_project_tcl message

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/report_failfast
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

Enhancements to report_failfast (xilinx::designutils)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/report_failfast
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

Enhancements to report_failfast (xilinx::designutils) (2018.2)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/report_failfast
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

Runtime enhancements to report_failfast (xilinx::designutils)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl
tclapp/xilinx/designutils/revision_history.txt

Various enhancements to prettyTable (xilinx::designutils)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

For 2018.2 (branch 2018.2-dev)

Fix issue with report_failfast + enhancement to prettyTable (xilinx::designutils)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/get_sll_nets.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/prettyTable.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

Pull request for designutils for 2019.1-dev

Added support for newer architectures (report_failfast, get_sll_nets, get_sll_nodes). Major enhancements (prettyTable)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt
tclapp/xilinx/designutils/tclIndex

Pull request for designutils for 2019.1-dev

Added support for US+ -1LV/-2LV (xilinx::designutils::report_failfast)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

Pull request for designutils for 2019.1-dev

Added support for Vivado patches (report_failfast)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

Pull request for designutils for 2019.1

Added support for updated report_control_sets format (report_failfast)

---

tclapp/xilinx/ultrafast/report_io_reg.tcl

add support for KU+, VU+, RFSOC, HBM, 58G

---

tclapp/xilinx/ultrafast/app.xml
tclapp/xilinx/ultrafast/checklist_pkg.tcl
tclapp/xilinx/ultrafast/pkgIndex.tcl
tclapp/xilinx/ultrafast/report_io_reg.tcl
tclapp/xilinx/ultrafast/revision_history.txt

This pull request is for Vivado 2019.1 (master)

Enhancements to report_io_reg (xilinx::ultrafast)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/doc/report_gtye5_refclk_summary
tclapp/xilinx/designutils/report_gtye5_refclk_summary.tcl
tclapp/xilinx/designutils/tclIndex
tclapp/xilinx/designutils/test/test.tcl

New tcl proc named report_gtye5_refclk_summary for Designutils app of Xilinx

New tcl proc named report_gtye5_refclk_summary for Design Utils app of Xilinx

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/report_gtye5_refclk_summary
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_gtye5_refclk_summary.tcl
tclapp/xilinx/designutils/revision_history.txt
tclapp/xilinx/designutils/tclIndex
tclapp/xilinx/designutils/test/report_gtye5_test.tcl
tclapp/xilinx/designutils/test/test.tcl

For Vivado 2020.2. on Git branch 2020.2-dev

Enhancements to report_gtye5_refclk_summary (xilinx::designutils)

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/report_gtye5_refclk_summary.tcl
tclapp/xilinx/designutils/revision_history.txt

This pull request is for Vivado 2020.2 and later. Please update the XML catalogs accordingly.

Enhancements to xilinx::designutils - Vivado 2020.2

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/report_failfast
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/report_gtye5_refclk_summary.tcl
tclapp/xilinx/designutils/revision_history.txt

This pull request is for Vivado 2020.3 and later. Please update the XML catalogs accordingly.

Enhancements to xilinx::designutils - Vivado 2020.3

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/report_failfast
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/report_gt_refclk_summary.tcl
tclapp/xilinx/designutils/revision_history.txt

Pull request for Vivado 2021.1

Enhancements to report_gt_refclk_summary and report_failfast (xilinx::designutils)

---

tclapp/aldec/activehdl/activehdl.tcl
tclapp/aldec/activehdl/app.xml
tclapp/aldec/activehdl/common/helpers.tcl
tclapp/aldec/activehdl/common/pkgIndex.tcl
tclapp/aldec/activehdl/common/sim.tcl
tclapp/aldec/activehdl/pkgIndex.tcl
tclapp/aldec/activehdl/register_options.tcl
tclapp/aldec/activehdl/revision_history.txt
tclapp/aldec/activehdl/sim.tcl
tclapp/aldec/riviera/app.xml
tclapp/aldec/riviera/common/helpers.tcl
tclapp/aldec/riviera/common/pkgIndex.tcl
tclapp/aldec/riviera/common/sim.tcl
tclapp/aldec/riviera/pkgIndex.tcl
tclapp/aldec/riviera/register_options.tcl
tclapp/aldec/riviera/revision_history.txt
tclapp/aldec/riviera/riviera.tcl
tclapp/aldec/riviera/sim.tcl

SPT81328 - Xilinx RAMB36E5 entity missing in unisim library
SPT81050 - How to simulate new Xilinx Versal Primitives ?
BKO1681 - Support for int_compile_glbl switch in launch_simulation command

1.31 SPT81328, SPT81050, BKO1681

---

tclapp/aldec/activehdl/activehdl.tcl
tclapp/aldec/activehdl/app.xml
tclapp/aldec/activehdl/common/helpers.tcl
tclapp/aldec/activehdl/common/pkgIndex.tcl
tclapp/aldec/activehdl/common/sim.tcl
tclapp/aldec/activehdl/pkgIndex.tcl
tclapp/aldec/activehdl/register_options.tcl
tclapp/aldec/activehdl/revision_history.txt
tclapp/aldec/activehdl/sim.tcl
tclapp/aldec/riviera/app.xml
tclapp/aldec/riviera/common/helpers.tcl
tclapp/aldec/riviera/common/pkgIndex.tcl
tclapp/aldec/riviera/common/sim.tcl
tclapp/aldec/riviera/pkgIndex.tcl
tclapp/aldec/riviera/register_options.tcl
tclapp/aldec/riviera/revision_history.txt
tclapp/aldec/riviera/riviera.tcl
tclapp/aldec/riviera/sim.tcl

SPT81535 - addsc: symbol lookup error: [Zynq ultra scale RFSoC through SystemC TLM Flow]

SPT81535 - addsc: symbol lookup error: [Zynq ultra scale RFSoC through SystemC TLM Flow]

---

tclapp/aldec/activehdl/activehdl.tcl
tclapp/aldec/activehdl/app.xml
tclapp/aldec/activehdl/common/helpers.tcl
tclapp/aldec/activehdl/common/pkgIndex.tcl
tclapp/aldec/activehdl/common/sim.tcl
tclapp/aldec/activehdl/pkgIndex.tcl
tclapp/aldec/activehdl/register_options.tcl
tclapp/aldec/activehdl/revision_history.txt
tclapp/aldec/activehdl/sim.tcl
tclapp/aldec/riviera/app.xml
tclapp/aldec/riviera/common/helpers.tcl
tclapp/aldec/riviera/common/pkgIndex.tcl
tclapp/aldec/riviera/common/sim.tcl
tclapp/aldec/riviera/pkgIndex.tcl
tclapp/aldec/riviera/register_options.tcl
tclapp/aldec/riviera/revision_history.txt
tclapp/aldec/riviera/riviera.tcl
tclapp/aldec/riviera/sim.tcl

BKO1750 - Add support for GUI mode when lauchning simulation with script_only

BKO1750 - Add support for GUI mode when lauchning simulation with script_only

---

tclapp/xilinx/designutils/report_gt_refclk_summary.tcl

• When a quad has interfaces connected but without any valid interface parameters, the reported REFCLK summary for this quad may be incorrect. This includes reporting incorrect REFCLK frequency and/or ParentIP
• When an interface is not connected to Xilinx IP nor bridge_ip, the interface parameters are invalid
• When an interface is connected manually, and if the parent IP interface parameters are not properly propagated to the GT quad, the script may misinterpret the GT interface parameters and report incorrect values in the summary

updated Reference clock data and messaging for better understanding for user.2023.2

---

tclapp/xilinx/designutils/report_gt_refclk_summary.tcl

updated refclock data and messaging for better understanding for users. 
•	When a quad has interfaces connected but without any valid interface parameters, the reported REFCLK summary for this quad may be incorrect. This includes reporting incorrect REFCLK frequency and/or ParentIP
•	When an interface is not connected to Xilinx IP nor bridge_ip, the interface parameters are invalid
•	When an interface is connected manually, and if the parent IP interface parameters are not properly propagated to the GT quad, the script may misinterpret the GT interface parameters and report incorrect values in the summary

updated refclock data and messaging

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_gt_refclk_summary.tcl
tclapp/xilinx/designutils/revision_history.txt

Merged enhancements to report_gt_refclk_summary (xilinx::designutils).

Update to xilinx::designutils for 2023.2-dev

---

tclapp/xilinx/designutils/report_gt_refclk_summary.tcl

updated refclock summary report to capture both multi and single clock tests: 2023.1

2023.1 dev: updated refclock summary report to capture both multi and single clock tests

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_gt_refclk_summary.tcl
tclapp/xilinx/designutils/revision_history.txt

Merged enhancements to report_gt_refclk_summary (xilinx::designutils).

Update to xilinx::designutils for 2023.1-dev

---

tclapp/aldec/activehdl/activehdl.tcl
tclapp/aldec/activehdl/app.xml
tclapp/aldec/activehdl/common/helpers.tcl
tclapp/aldec/activehdl/common/pkgIndex.tcl
tclapp/aldec/activehdl/common/sim.tcl
tclapp/aldec/activehdl/pkgIndex.tcl
tclapp/aldec/activehdl/register_options.tcl
tclapp/aldec/activehdl/revision_history.txt
tclapp/aldec/activehdl/sim.tcl
tclapp/aldec/riviera/app.xml
tclapp/aldec/riviera/common/helpers.tcl
tclapp/aldec/riviera/common/pkgIndex.tcl
tclapp/aldec/riviera/common/sim.tcl
tclapp/aldec/riviera/pkgIndex.tcl
tclapp/aldec/riviera/register_options.tcl
tclapp/aldec/riviera/revision_history.txt
tclapp/aldec/riviera/riviera.tcl
tclapp/aldec/riviera/sim.tcl

Add support for VHDL2019

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/report_failfast.tcl
tclapp/xilinx/designutils/revision_history.txt

This pull request is for Vivado 2023.2 to be merged in Git branch master

Enhancements to report_failfast (xilinx::designutils) for 2023.2

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/disable_equiv_vivado_directives
tclapp/xilinx/designutils/doc/enable_equiv_vivado_directives
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/revision_history.txt
tclapp/xilinx/designutils/run_equiv_vivado_directives.tcl
tclapp/xilinx/designutils/tclIndex

This pull request is for Vivado 2024.2 and should be merged inside the Git branch master. It includes the pull requests #816 / #817

Added run_equiv_vivado_directives.tcl (xilinx::designutils) for Vivado 2024.2

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/doc/disable_equiv_vivado_directives
tclapp/xilinx/designutils/doc/enable_equiv_vivado_directives
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/revision_history.txt
tclapp/xilinx/designutils/run_equiv_vivado_directives.tcl
tclapp/xilinx/designutils/tclIndex

This pull request is for Vivado 2025.1 and should be merged inside the branch 2025.1-dev

Added run_equiv_vivado_directives (xilinx::designutils) for 2025.1-dev

---

tclapp/xilinx/designutils/app.xml
tclapp/xilinx/designutils/designutils.tcl
tclapp/xilinx/designutils/pkgIndex.tcl
tclapp/xilinx/designutils/revision_history.txt
tclapp/xilinx/designutils/run_equiv_vivado_directives.tcl
tclapp/xilinx/designutils/tclIndex

Updated equivalent mapping script for new strategies in 2025.2

2025.2 dev
